In [3]:
import torch

def pprint(name, ten):
    print(name,":",ten, ten.shape)
    
tensor1d = torch.tensor([1, 2, 3])
pprint("1d",tensor1d)

tensor2d_1= torch.tensor([[1,2,3]])
pprint("2d_1",tensor2d_1)

tensor2d_2= torch.tensor([[1,2,3],[4,5,6]])
pprint("2d_2",tensor2d_2)

tensor3d = torch.tensor([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
pprint("3d",tensor3d)

tensor4d = torch.tensor([[[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]]])
pprint("4d",tensor4d)


tensor4d_2 = torch.tensor([[[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]],[[[17,18,19,20],[21,22,23,24]],[[25,26,27,28],[29,30,31,32]]]])
pprint("4d",tensor4d_2)



1d : tensor([1, 2, 3]) torch.Size([3])
2d_1 : tensor([[1, 2, 3]]) torch.Size([1, 3])
2d_2 : tensor([[1, 2, 3],
        [4, 5, 6]]) torch.Size([2, 3])
3d : tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],

        [[ 9, 10, 11, 12],
         [13, 14, 15, 16]]]) torch.Size([2, 2, 4])
4d : tensor([[[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8]],

         [[ 9, 10, 11, 12],
          [13, 14, 15, 16]]]]) torch.Size([1, 2, 2, 4])
4d : tensor([[[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8]],

         [[ 9, 10, 11, 12],
          [13, 14, 15, 16]]],


        [[[17, 18, 19, 20],
          [21, 22, 23, 24]],

         [[25, 26, 27, 28],
          [29, 30, 31, 32]]]]) torch.Size([2, 2, 2, 4])


questo e' come nel capitolo 3.6.2 keys (ossia 2,6,2)

In [9]:
t = torch.rand(2,6,3)
pprint("t",t)
pprint("TT",t.transpose(1,2))

t : tensor([[[0.4784, 0.5354, 0.2389],
         [0.2243, 0.5836, 0.0325],
         [0.2718, 0.1980, 0.1928],
         [0.5205, 0.2182, 0.7934],
         [0.3622, 0.8294, 0.4856],
         [0.8127, 0.6451, 0.0170]],

        [[0.8094, 0.4747, 0.2746],
         [0.7292, 0.0957, 0.1801],
         [0.4040, 0.3692, 0.5582],
         [0.7754, 0.4829, 0.8159],
         [0.0162, 0.1492, 0.5853],
         [0.6125, 0.6610, 0.7357]]]) torch.Size([2, 6, 3])
TT : tensor([[[0.4784, 0.2243, 0.2718, 0.5205, 0.3622, 0.8127],
         [0.5354, 0.5836, 0.1980, 0.2182, 0.8294, 0.6451],
         [0.2389, 0.0325, 0.1928, 0.7934, 0.4856, 0.0170]],

        [[0.8094, 0.7292, 0.4040, 0.7754, 0.0162, 0.6125],
         [0.4747, 0.0957, 0.3692, 0.4829, 0.1492, 0.6610],
         [0.2746, 0.1801, 0.5582, 0.8159, 0.5853, 0.7357]]]) torch.Size([2, 3, 6])


In [2]:
tensor_2_6_2 = torch.tensor([[[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]],[[13,14],[15,16],[17,18],[19,20],[21,22],[23,24]]])
pprint("2.6.2",tensor_2_6_2)

tensor_2_6_2_1  = tensor_2_6_2.view(2,6,2,1)
pprint("2.6.2.1",tensor_2_6_2_1)

2.6.2 : tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8],
         [ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16],
         [17, 18],
         [19, 20],
         [21, 22],
         [23, 24]]]) torch.Size([2, 6, 2])
2.6.2.1 : tensor([[[[ 1],
          [ 2]],

         [[ 3],
          [ 4]],

         [[ 5],
          [ 6]],

         [[ 7],
          [ 8]],

         [[ 9],
          [10]],

         [[11],
          [12]]],


        [[[13],
          [14]],

         [[15],
          [16]],

         [[17],
          [18]],

         [[19],
          [20]],

         [[21],
          [22]],

         [[23],
          [24]]]]) torch.Size([2, 6, 2, 1])


Quando ricombini con view devi calcolare che moltiplicando il numero di elementi per ogni dimensione venga il numero di elementi nel tensor originale:

per tensor_2_6_2 che ha 24 elementi non e' lecito ad esempio fare 2_6_2_2. 

In [3]:
tensor_2_6_2_1_1 = tensor_2_6_2.view(2,6,2,1,1)
pprint("2_6_2_1_1",tensor_2_6_2_1_1)

2_6_2_1_1 : tensor([[[[[ 1]],

          [[ 2]]],


         [[[ 3]],

          [[ 4]]],


         [[[ 5]],

          [[ 6]]],


         [[[ 7]],

          [[ 8]]],


         [[[ 9]],

          [[10]]],


         [[[11]],

          [[12]]]],



        [[[[13]],

          [[14]]],


         [[[15]],

          [[16]]],


         [[[17]],

          [[18]]],


         [[[19]],

          [[20]]],


         [[[21]],

          [[22]]],


         [[[23]],

          [[24]]]]]) torch.Size([2, 6, 2, 1, 1])


Moltiplicazioni

In [22]:
m1=torch.tensor([[1,2,3],[4,5,6]])
pprint("m1",m1)

m2 = torch.tensor([[7,8],[9,10],[11,12]])
pprint("m2",m2)

pprint("m1xm1",m1*m1)

pprint("m1@m2",m1@m2)

pprint("m1@m1.T",m1@m1.T)

m3= torch.randint(1,9,(3,2))
m4=torch.randint(10,20,(2,6,3))
print(m3,"\n",m4)
pprint("m4@m3",m4@m3)

m1 : tensor([[1, 2, 3],
        [4, 5, 6]]) torch.Size([2, 3])
m2 : tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]]) torch.Size([3, 2])
m1xm1 : tensor([[ 1,  4,  9],
        [16, 25, 36]]) torch.Size([2, 3])
m1@m2 : tensor([[ 58,  64],
        [139, 154]]) torch.Size([2, 2])
m1@m1.T : tensor([[14, 32],
        [32, 77]]) torch.Size([2, 2])
tensor([[2, 1],
        [2, 6],
        [7, 2]]) 
 tensor([[[19, 16, 13],
         [19, 19, 16],
         [18, 14, 18],
         [19, 19, 17],
         [16, 17, 13],
         [13, 18, 16]],

        [[18, 10, 13],
         [15, 15, 18],
         [17, 18, 14],
         [19, 15, 11],
         [16, 14, 10],
         [11, 14, 18]]])
m3@m4 : tensor([[[161, 141],
         [188, 165],
         [190, 138],
         [195, 167],
         [157, 144],
         [174, 153]],

        [[147, 104],
         [186, 141],
         [168, 153],
         [145, 131],
         [130, 120],
         [176, 131]]]) torch.Size([2, 6, 2])


trasposte di tensor. transpose riceve le 2 dimensioni da swappare

In [6]:
pprint("X", tensor_2_6_2.transpose(0,1))
pprint("originale",tensor_2_6_2_1)
pprint("tensor_2_6_2.transpose(1,2)",tensor_2_6_2_1.transpose(1,2))



X : tensor([[[ 1,  2],
         [13, 14]],

        [[ 3,  4],
         [15, 16]],

        [[ 5,  6],
         [17, 18]],

        [[ 7,  8],
         [19, 20]],

        [[ 9, 10],
         [21, 22]],

        [[11, 12],
         [23, 24]]]) torch.Size([6, 2, 2])
originale : tensor([[[[ 1],
          [ 2]],

         [[ 3],
          [ 4]],

         [[ 5],
          [ 6]],

         [[ 7],
          [ 8]],

         [[ 9],
          [10]],

         [[11],
          [12]]],


        [[[13],
          [14]],

         [[15],
          [16]],

         [[17],
          [18]],

         [[19],
          [20]],

         [[21],
          [22]],

         [[23],
          [24]]]]) torch.Size([2, 6, 2, 1])
tensor_2_6_2.transpose(1,2) : tensor([[[[ 1],
          [ 3],
          [ 5],
          [ 7],
          [ 9],
          [11]],

         [[ 2],
          [ 4],
          [ 6],
          [ 8],
          [10],
          [12]]],


        [[[13],
          [15],
          [17],
          

In [14]:
t1=torch.rand(2,6,3)
t2=torch.rand(2,6,3)
print(t1,t2,torch.cat([t1,t2],dim=-1).shape)

tensor([[[0.0163, 0.5856, 0.4700],
         [0.9297, 0.5429, 0.4421],
         [0.6686, 0.3201, 0.6199],
         [0.6343, 0.1285, 0.9508],
         [0.3809, 0.7397, 0.3944],
         [0.6041, 0.6690, 0.7813]],

        [[0.7114, 0.3861, 0.6050],
         [0.2366, 0.0665, 0.5817],
         [0.1154, 0.4509, 0.4242],
         [0.2222, 0.0614, 0.7874],
         [0.6113, 0.9987, 0.9966],
         [0.6528, 0.7153, 0.1669]]]) tensor([[[0.2708, 0.4777, 0.6223],
         [0.5519, 0.5108, 0.5498],
         [0.5835, 0.7636, 0.0221],
         [0.7095, 0.7649, 0.0667],
         [0.7939, 0.7513, 0.0765],
         [0.9675, 0.6143, 0.1805]],

        [[0.5200, 0.2565, 0.3444],
         [0.4369, 0.9820, 0.1553],
         [0.6710, 0.2638, 0.3983],
         [0.4485, 0.3839, 0.4188],
         [0.4773, 0.0376, 0.2851],
         [0.6943, 0.6320, 0.0088]]]) torch.Size([2, 6, 6])
